from __future__ import annotations


BRAND_ARBITER_SCHEMA = {
    "type": "object",
    "properties": {
        "confidence": {"type": "string"},
        "evidence_strength": {"type": "string"},
        "brand_quality_score": {"type": "integer"},
        "creator_fit_score": {"type": "integer"},
        "outreach_readiness_score": {"type": "integer"},
        "risk_score": {"type": "integer"},
        "evidence_quality_score": {"type": "integer"},
        "brand_strengths": {"type": "array", "items": {"type": "string"}},
        "brand_weaknesses": {"type": "array", "items": {"type": "string"}},
        "risk_flags": {"type": "array", "items": {"type": "string"}},
        "why_this_brand": {"type": "string"},
        "why_now": {"type": "string"},
        "what_not_to_say": {"type": "array", "items": {"type": "string"}},
        "recommended_channel": {"type": "string"},
        "recommended_angle": {"type": "string"},
        "need_more_research": {"type": "boolean"},
        "research_gaps": {"type": "array", "items": {"type": "string"}},
        "media_enrichment_required": {"type": "boolean"},
        "verdict": {"type": "string"},
        "recommended_action": {"type": "string"},
        "personalization_gap": {"type": "boolean"},
        "signal_conflict": {"type": "boolean"},
    },
    "required": [
        "confidence",
        "evidence_strength",
        "brand_quality_score",
        "creator_fit_score",
        "outreach_readiness_score",
        "risk_score",
        "evidence_quality_score",
        "brand_strengths",
        "brand_weaknesses",
        "risk_flags",
        "why_this_brand",
        "why_now",
        "what_not_to_say",
        "recommended_channel",
        "recommended_angle",
        "need_more_research",
        "research_gaps",
        "media_enrichment_required",
        "verdict",
        "recommended_action",
        "personalization_gap",
        "signal_conflict",
    ],
}


MEDIA_REPORT_SCHEMA = {
    "type": "object",
    "properties": {
        "content_topics": {"type": "array", "items": {"type": "string"}},
        "brand_mentions": {"type": "array", "items": {"type": "string"}},
        "audience_tone": {"type": "string"},
        "comment_themes": {"type": "array", "items": {"type": "string"}},
        "comment_sentiment": {"type": "string"},
        "recurring_requests": {"type": "array", "items": {"type": "string"}},
        "risk_flags": {"type": "array", "items": {"type": "string"}},
        "creator_style": {"type": "string"},
        "integration_fit": {"type": "string"},
        "use_as_signal": {"type": "array", "items": {"type": "string"}},
        "do_not_use_as_signal": {"type": "array", "items": {"type": "string"}},
    },
    "required": [
        "content_topics",
        "brand_mentions",
        "audience_tone",
        "comment_themes",
        "comment_sentiment",
        "recurring_requests",
        "risk_flags",
        "creator_style",
        "integration_fit",
        "use_as_signal",
        "do_not_use_as_signal",
    ],
}
